version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017' # Optional, for accessing from host
    networks:
      custom_net:
        aliases:
          - mongo

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skillset-app
    ports:
      - "4000:5001" # Assuming backend exposes 5001
    environment:
      - MONGO_URI=mongodb://mongo:27017/skillset
    depends_on:
      - mongo
    networks:
      - custom_net

networks:
  custom_net:
    driver: bridge
