services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - custom_net

  app:
    image: jatinjb05/skillset:latest
    container_name: skillset-app
    ports:
      - "4000:5000"
    depends_on:
      - mongo
    networks:
      - custom_net
    environment:
      - MONGO_URI=mongodb://mongo:27017/SkillDB
      - PORT=5000
      - JWT_SECRET=your_jwt_secret_here

networks:
  custom_net:
    driver: bridge
