version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - custom_net

  app:
    image: jatinjb05/skillset:latest
    container_name: skillset-app
    ports:
      - "4000:5000"
    depends_on:
      - mongo
    networks:
      - custom_net

networks:
  custom_net:
    driver: bridge
